#Site Config
baseurl: ""
url: "http://www.behicakgun.com"
description: "Sales Operations pro who dabbles in web development, writing and photography to expand his creativity and pursue a life well lived."
collections:
  posts:
    output: true
    permalink: /posts/:path/
  projects:
    output: true
    permalink: /projects/:path/

# Site settings
title: BehicAkgun.com

# Build settings
markdown: kramdown
permalink: pretty

#Icons
email_address: "behica@gmail.com"
github: behica
linkedin: https://www.linkedin.com/in/behic/


#Scripts
google_analytics: "UA-96057240-1"
