#Site Config
baseurl: ""
url: "http://www.behicakgun.com"
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# Site settings
title: BehicAkgun.com

# Build settings
markdown: kramdown
permalink: pretty

#Icons
email_address: "behica@gmail.com"
github: behica
linkedin: https://www.linkedin.com/in/behic/


#Scripts
google_analytics: "UA-96057240-1"
